<?php if (Mage::getStoreConfig('socialshare/general/enabled')) : ?>

	<?php if(!Mage::getStoreConfig('opengraphtags/conf/active')) : ?>
		<!-- Facebook Social Init -->
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
	<?php endif; ?>
	
	<?php if (Mage::getStoreConfig('socialshare/general/show_count')) : ?>
	<div class="social_buttons withcount">    
		<?php if (Mage::getStoreConfig('socialshare/general/facebook_btn')) : ?>
		<!-- Facebook -->
		<span class="facebookContainer">
			<div class="fb-like" data-href="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" data-send="false" data-layout="button_count" data-width="150" data-show-faces="false"></div>
		</span>
		<?php endif; ?>
		
		<?php if (Mage::getStoreConfig('socialshare/general/twitter_btn')) : ?>
		<!-- Twitter -->
		<div class="twitterContainer">
			<a href="//twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="<?php echo Mage::getStoreConfig('socialshare/general/twitter_acc'); ?>">Tweet</a>
		</div>
		<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>    
		<?php endif; ?>
		
		<?php if (Mage::getStoreConfig('socialshare/general/google_btn')) : ?>
		<!-- Google +1 -->
		<script type="text/javascript">
		  (function() {
			var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
			po.src = 'https://apis.google.com/js/plusone.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  })();
		</script>
		<div class="gPlusContainer">
			<g:plusone size="medium"></g:plusone>
		</div>
		<?php endif; ?>
		
		<?php if (Mage::getStoreConfig('socialshare/general/pinter_btn')) : ?>
		<?php
		$data = "?url=".Mage::helper('core/url')->getCurrentUrl();
		$product = Mage::registry('current_product'); 
		if(isset($product) && is_object($product)){
		    $data .= "&media=".$this->htmlEscape($product->getImageUrl());
		    $data .= "&description=".$this->stripTags($product->getShortDescription());
		}
		?>
		<!-- Pinterest -->
		<div class="pinterestContainer">
			<a href="//pinterest.com/pin/create/button/<?php echo $data?>" data-pin-do="buttonPin" data-pin-config="beside">
				<img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" />
			</a>
		</div>
		<?php endif; ?>	
	</div>
	<?php else : ?>
	<div class="social_buttons withoutcount">
		<?php if (Mage::getStoreConfig('socialshare/general/facebook_btn')) : ?>
		<!-- Facebook -->
		<div class="facebookContainer">
			<div class="fb-like" data-href="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" data-send="false" data-layout="button" data-width="150" data-show-faces="false"></div>
		</div>
		<?php endif; ?>
		
		<?php if (Mage::getStoreConfig('socialshare/general/twitter_btn')) : ?>
		<!-- Twitter -->
		<div class="twitterContainer">
			<a href="https://twitter.com/share" class="twitter-share-button" data-count="none" data-via="<?php echo Mage::getStoreConfig('socialshare/general/twitter_acc'); ?>">Tweet</a>
			<script type="text/javascript" src="https://platform.twitter.com/widgets.js"></script>  
		</div>
		<?php endif; ?>
		
		<?php if (Mage::getStoreConfig('socialshare/general/google_btn')) : ?>
		<!-- Google +1 -->
		<div class="gPlusContainer">
			<script type="text/javascript">
			  (function() {
				var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				po.src = 'https://apis.google.com/js/plusone.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
			  })();
			</script>
			<g:plusone size="Standard" class="g-plusone" annotation="none" ></g:plusone>
		</div>
		<?php endif; ?>
		
		<?php if (Mage::getStoreConfig('socialshare/general/pinter_btn')) : ?>
		<?php
		$data = "?url=".Mage::helper('core/url')->getCurrentUrl();
		$product = Mage::registry('current_product'); 
		if(isset($product) && is_object($product)){
		    $data .= "&media=".$this->htmlEscape($product->getImageUrl());
		    $data .= "&description=".$this->stripTags($product->getShortDescription());
		}
		?>
		<!-- Pinterest -->
		<div class="pinterestContainer">
			<a href="//pinterest.com/pin/create/button/<?php echo $data; ?>" data-pin-do="buttonPin" data-pin-config="none">
				<img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" />
			</a>
		</div>
		<?php endif; ?>	
	</div>
	<?php endif; ?>

<div class="clearfix"></div>
<?php endif; ?>